### ISSUE TITLE
make all fails

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-alyalyaly123#1]
The command `make all` fails:

> root@dc62bad0d682:/depsolver/to-test# make all
> ./install_deps.sh
> make: execvp: ./install_deps.sh: Permission denied
> Makefile:7: recipe for target 'deps' failed
> make: *** [deps] Error 127 

Please mark scripts as executable. On Linux, `chmod +x`; on Windows `git update-index --chmod=+x` (see https://stackoverflow.com/a/21694391)

**Comment by rgrig** [comment]
Also, the script `compile.sh` seems to compile all files in the directory `src`, but there is no such directory.
Also, the file `Main.Java` should probably be `dependency/Main.java` (note both the wrong directory/package and the wrong extension).

**Comment by rgrig** [comment]
After fixing the above problems locally (but you *must* fix them in the repo), I get a compilation error on `import org.json.*`. In which library is that package? How do you install it? Add commands for installing it somewhere (the most likely right place would be the `install_deps.sh` script).

**Comment by rgrig** [comment]
Here is a screencast in which I run by hand the commands from the testing scripts. Perhaps it clarifies which commands are expected to work: https://asciinema.org/a/nd8L1pl7kmtUUTE3jiizWQR9q

**Comment by alyalyaly123** [comment]
Sorry I'm not 100% certain of what to do with it, I've tried running the following code  : 
____________________________________________________________________
git update-index --chmod=+x compile.sh install_deps.sh run_tests.sh solve
  git add compile.sh install_deps.sh run_tests.sh solve
  git commit -m "made executable"
____________________________________________________________________
on githubs desktop app but it doesn't seem to have affected the leaderboard scores (Unless that is manually done).

**Comment by rgrig** [comment]
This seems to be fixed now, so I'm closing. Thanks.

The scoreboard updates itself about once per hour. You don't have more points because of other issues which I'll file separately.
